### ISSUE TITLE
nextjsで、直接ページを開いた時にエラーが表示される。

### ISSUE THREAD

**Issue by mori-goq** [GoQSystemInc/GoqZipCode#21]
## 症状
nextjsで、最初に開いたページで、直ぐに`new GoqZipCode()`を記述していると、エラーになりページが開けません。
`next/link`でのページ遷移や、ページを開いた後少し経って`new GoqZipCode()`する場合はエラーになりません。

## エラー文
`Error: Can't read the data of 'the loaded zip file'. Is it in a supported JavaScript type (String, Blob, ArrayBuffer, etc) ?`

**Comment by iwata-goq** [comment]
@mori-goq 
メモ用で残しているので気にしないでください。

・Next.jsなどのssrがなされる場合、クライアントサイドでインスタンス化する必要がでてくる（クライアントサイドライブラリのため）。
・今回は `process.browser`で対応できる。
・ライブラリ側ではssrかどうかの判断はできないので、開発者で切り分けてもらうしかない気がする。

Readmeに上記のことを要約して追記する。

**Comment by mori-goq** [comment]
@iwata-goq 

```
const goqZipCode = process.browser && new GoqZipCode()
```
は関数の外に記述する
（関数内だと、何度も発火してzipファイルをその都度ダウンロードしていた）

**Comment by iwata-goq** [comment]
@mori-goq 
なるほど、再レンダリングのたびにフェッチしていたってことですな。
了解です！ありがとうございます。
